### ISSUE TITLE
No Autolayout?

### ISSUE THREAD

**Issue by fabiosoft** [Friend-LGA/LGRefreshView#2]
Doesn't it uses autolayout?
Because it's not centered in middle of the scroll view (uitableview)

**Comment by julioz** [comment]
@Friend-LGA I'm having the same problem - the first time I pull-to-refresh the view is not centered (it goes right aligned) but after that all the next refreshes show the view centered.

**Comment by Friend-LGA** [comment]
Check out demo project, everything is ok, even on iOS 9. Can you give me example with existing problem?

**Comment by acerbetti** [comment]
I'm facing the same issue, I'm sending a demo project by email, so you can verify it

Thanks
